# Generated by Django 3.2 on 2021-05-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(db_column='key', max_length=50, null=True)),
                ('FileName', models.FileField(db_column='FileField', null=True, upload_to='')),
            ],
        ),
    ]
